### ISSUE TITLE
Add red star marking the element required to more elements

### ISSUE THREAD

**Issue by Thommas2316** [contember/interface#438]
Hi all,

not long time ago I created issue #381 which David fixed already. 
However, I found few more elements that are missing this flag.
I'd like to try to send a PR with fix, just need to ask this, so I know I'm not out my depths here :D
 
Would it be ok to just (in cargo-cult manner) just add `required={props.required}` to `FieldContainer` (where props do carry this info ofc) as David did in his PR ? 
Or does it trigger some behavior on the element that I need to watch out for ? Like, for instance, if `required` prop is set on `FieldContainer` it tries to trigger some sort of validation of children, that not all children can fulfill... 

If the task is only about propagating the `required` prop - I think I could try to fix it myself via PR. What are the next steps if it is the case ?

Thank you

**Comment by attitude** [comment]
Hi @Thommas2316, thank you for your patience.

Your issues with display of asterisk should now all be resolved in [v1.2](https://github.com/contember/interface/releases/tag/v1.2.0). I will close this issue, however, feel free to reopen if issues persist.

*As a side-note, the required prop on the UI FieldContainer component does not trigger any validations. Its responsibility is only to display the asterisk.*

Thanks for the report 🙌 

<img width="931" alt="Working example how to display required asterisk next to a label" src="https://github.com/contember/interface/assets/387611/232ff100-e231-4970-9d70-757f6e81b16d">
