### ISSUE TITLE
Stack ts error

### ISSUE THREAD

**Issue by iBobik** [contember/interface#457]
Hi,
Stack component works, but TypeScript reports this error:

<img width="639" alt="Snímek obrazovky 2023-01-17 v 22 58 59" src="https://user-images.githubusercontent.com/614232/213022011-4bf0d8dc-f726-4505-ba9d-51e3e47d0d3e.png">

```
Type '{ children: Element[]; direction: "horizontal"; gap: "small"; align: "center"; }' is missing the following properties from type 'Pick<StackProps, "slot" | "style" | "title" | "children" | "key" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 257 more ... | "wrap">': onResize, onResizeCapturets(2739)
```

@contember/admin 1.1.0-beta.2

**Comment by iBobik** [comment]
This fixed error, but it does not make sense for me to require it.

```
<Stack direction="horizontal" gap="small" align="center" onResize={undefined} onResizeCapture={undefined}>
```

**Comment by jonasNobile** [comment]
Hi Honza,

You probably have an old version of the `@types/react` package. We've updated the React version to 18 in new Admin version. Please try to update types and react in your project.


```json
    "dependencies": {
        ...
        "react": "^18",
        "react-dom": "^18",
        ...
    },
    "devDependencies": {
        ...
        "@types/react": "^18",
        "@types/react-dom": "^18",
        ...
    }
```

**Comment by iBobik** [comment]
Yes, this solved it, thank you.

I used React 17 because it was in the project template and contember/admin
did not complained when upgraded. 🙂

Why is React peer dependency? In Contember projects it make sense for me to
use recommanded deps and versions, so I would ideally have only @contember
packages in package.json

18. 1. 2023 10:52:01, Jonáš Nobile ***@***.***> napsal:
