### ISSUE TITLE
`<RichTextField>`: wrong caret position while typing

### ISSUE THREAD

**Issue by FilipChalupa** [contember/interface#458]
![caret](https://user-images.githubusercontent.com/1045362/214287523-286fc377-aa4f-4d8e-9066-1508e0b96919.gif)

**Comment by FilipChalupa** [comment]
- `@contember/admin@1.1.0-alpha.16`
- Chrome 109, MS Edge 108
- Pure `<RichTextField />` from `@contember/admin`

Happens to me in newly created block inside `<BlockEditor />`.

**Comment by attitude** [comment]
Hi @FilipChalupa, I tried in 1.2 to replicate the issue, however it seems to be already either resolved or is not replicable by us.

![rich-text-cursor](https://github.com/contember/interface/assets/387611/fa0e11db-b539-4044-b782-9782019459fb)

Try the current [1.2 release](https://github.com/contember/interface/releases/tag/v1.2.0) whether the issue persist. I will close the issue for now as it seams to be working as expected, however, feel free to reopen if you find the above version not fixing your issue and we can try to pin-point your issue together later on.

_Tested on MacOS:_
- Chrome 117.0.5938.62 (Official Build) (arm64)
- Firefox 117.0.1 (64-bit)
- Safari 17.0 (19616.1.27.111.16)
- Safari Technology Preview, Release 178 (Safari 17.0, WebKit 19617.1.6)
