### ISSUE TITLE
SlugField appearance without unpersistedHardPrefix

### ISSUE THREAD

**Issue by iBobik** [contember/interface#459]
When not using unpersistedHardPrefix then the field looks broken:

<img width="793" alt="Snímek obrazovky 2023-01-24 v 19 41 33" src="https://user-images.githubusercontent.com/614232/214380378-2da62d44-2e9b-404e-b561-7d85f99e784e.png">
<img width="794" alt="Snímek obrazovky 2023-01-24 v 19 41 40" src="https://user-images.githubusercontent.com/614232/214380388-0695847e-3e7e-457d-be67-c88a6f9fc797.png">

```
<SlugField field="slug" label="Slug" derivedFrom="name" readOnly={edit} />
```

**Comment by attitude** [comment]
I tested it and it is already fixed in 1.2.
Thanks for the report 🙌 

<img width="808" alt="Screenshot 2023-09-12 at 15 34 13" src="https://github.com/contember/interface/assets/387611/77c799b9-0cb3-4c68-a771-adf85adfcaed">
