### ISSUE TITLE
Deleting top-level entities is not yet implemented.

### ISSUE THREAD

**Issue by iBobik** [contember/interface#460]
Even entities without relations can not be deleted in an admin.

**Comment by FilipChalupa** [comment]
To delete top level entity I usually use `<DeleteEntityButton immediatePersist />` inside `<DataGridPage>`. Is that it?

![image](https://user-images.githubusercontent.com/1045362/214394548-0e6c0a08-b4ee-4b46-a0bb-646bbf29882f.png)

![image](https://user-images.githubusercontent.com/1045362/214394976-b3a4d86e-6247-43eb-bbf8-6f01243705c0.png)

**Comment by iBobik** [comment]
No, I’ve added it to the EditPage.

24. 1. 2023 20:54:19, Filip Chalupa ***@***.***> napsal:

**Comment by matej21** [comment]
Hi,
in top level entitty delete is supported since 1.2.0 https://github.com/contember/interface/releases/tag/v1.2.0
