### ISSUE TITLE
`<HiddenField>` requires label prop in v1.1.0-rc.4

### ISSUE THREAD

**Issue by Vrtak-CZ** [contember/interface#476]
I don't know with the version it was introduced but in [v1.1.0-rc.4](https://github.com/contember/interface/releases/tag/v1.1.0-rc.4) HiddelField requires `label` prop. But `label` prop does not make any sense in `HiddenField` am I wrong?

**Comment by matej21** [comment]
You are right, it makes no sense and it is there for a very long time :) usually, I explictly pass `undefined` as a label.

**Comment by Vrtak-CZ** [comment]
Btw [documentation](https://docs.contember.com/reference/admin/api/components/form-fields/#hidden-field) does not reflect that
